import re

old_sql = """
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Breakfast', 'Cereals with Milk', 160, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Breakfast', 'Canned Juice', 120, true, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Breakfast', 'Pancake', 250, true, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Breakfast', 'Puri Bhaji', 250, true, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Breakfast', 'Tawa Paratha with Stuffing of Choice (2 pcs)', 300, true, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Breakfast', 'Tandoori Paratha with Stuffing of Choice (2 pcs)', 350, true, 6),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Breakfast', 'Chole Bhature', 300, true, 7),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Breakfast', 'Poha / Vermicelli Upma / Rawa Choice', 250, true, 8),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Breakfast', 'Cutlet / Aloo Bonda / Bread Pakora / Bread Roll (2 pcs)', 150, true, 9),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Breakfast', 'Plain Dosa', 250, true, 10),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Breakfast', 'Onion / Masala Dosa', 300, true, 11),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Breakfast', 'Paneer / Cheese Dosa', 400, true, 12),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Breakfast', 'Utthapam / Idli / Medu Vada', 250, true, 13),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Egg to Order', 'Cheese Omelette', 250, false, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Egg to Order', 'Bread Omelette', 200, false, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Egg to Order', 'Boiled Egg (2 pcs)', 100, false, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Egg to Order', 'Egg Bhurji', 180, false, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Egg to Order', 'Sunny Side Up / Half Fry / Egg Poach (2 pcs)', 150, false, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Egg to Order', 'Scrambled Egg (2 pcs)', 180, false, 6),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Starters – Veg', 'Chilli Paneer', 400, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Starters – Veg', 'Honey Chilli Potato', 300, true, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Starters – Veg', 'Cheese Balls', 300, true, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Starters – Veg', 'Crispy Corn', 400, true, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Starters – Veg', 'Veg Spring Roll', 350, true, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Starters – Veg', 'Veg Kathi Roll', 350, true, 6),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Starters – Veg', 'Mushroom Tikka', 500, true, 7),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Starters – Veg', 'Paneer Tikka', 600, true, 8),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Starters – Veg', 'Soya Chaap / Soya Malai Chaap', 300, true, 9),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Starters – Non-Veg', 'Non-Veg Spring Roll', 500, false, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Starters – Non-Veg', 'Non-Veg Kathi Roll', 500, false, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Starters – Non-Veg', 'Chilli Chicken / Chicken 65', 600, false, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Starters – Non-Veg', 'Chicken Seekh Kabab', 650, false, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Starters – Non-Veg', 'Chicken Malai Tikka', 650, false, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Starters – Non-Veg', 'Chicken Tikka', 600, false, 6),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Starters – Non-Veg', 'Bhatti Murg', 800, false, 7),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Starters – Non-Veg', 'Chicken Haryali Tikka', 650, false, 8),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Soup', 'Cream of Tomato', 300, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Soup', 'Manchow Soup', 250, true, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Soup', 'Dhaniya Shorba', 250, true, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Soup', 'Sweet Corn', 250, true, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Soup', 'Minestrone', 350, true, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Soup', 'Chicken Clear Soup', 250, false, 6),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Soup', 'Chicken Coriander Soup', 250, false, 7),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Salad', 'Green Salad', 150, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Salad', 'Russian / Kimchi / Finger Salad', 250, true, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Salad', 'Protein Salad', 250, true, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Paneer', 'Kadahi Paneer', 550, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Paneer', 'Shahi Paneer', 550, true, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Paneer', 'Paneer Do Pyaza', 550, true, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Paneer', 'Makhani Paneer', 550, true, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Paneer', 'Paneer Butter Masala', 550, true, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Paneer', 'Methi Malai Paneer', 550, true, 6),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Paneer', 'Paneer Lababdar', 550, true, 7),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Paneer', 'Palak Paneer', 550, true, 8),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Paneer', 'Paneer Pasanda', 550, true, 9),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Paneer', 'Paneer Kofta', 550, true, 10),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Paneer', 'Paneer Bhurji', 550, true, 11),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Paneer', 'Paneer Tikka Masala', 650, true, 12),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Seasonal Vegetable', 'Bhindi Do Pyaza', 350, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Seasonal Vegetable', 'Aloo Jeera', 300, true, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Seasonal Vegetable', 'Aloo Gobhi Adrakhi', 350, true, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Seasonal Vegetable', 'Heeng Aloo Beans', 350, true, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Seasonal Vegetable', 'Achari Baigan', 350, true, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Seasonal Vegetable', 'Dum Aloo', 400, true, 6),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Seasonal Vegetable', 'Matar Mushroom', 550, true, 7),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Seasonal Vegetable', 'Mushroom Butter Masala', 550, true, 8),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Seasonal Vegetable', 'Mushroom Do Pyaza', 550, true, 9),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Seasonal Vegetable', 'Mushroom Masala', 550, true, 10),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Seasonal Vegetable', 'Vegetable in Sweet and Sour Gravy', 350, true, 11),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Seasonal Vegetable', 'Manchurian Gravy', 400, true, 12),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Chicken', 'Kadahi Chicken', 650, false, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Chicken', 'Chicken Curry', 650, false, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Chicken', 'Chicken Masala', 650, false, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Chicken', 'Kali Mirch Chicken', 700, false, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Chicken', 'Chicken Masala Tikka', 650, false, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Chicken', 'Mughlai Chicken', 700, false, 6),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Chicken', 'Afghani Chicken', 700, false, 7),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Chicken', 'Butter Chicken', 700, false, 8),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Chicken', 'Handi Chicken', 650, false, 9),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Chicken', 'Rogan Josh Chicken', 650, false, 10),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Chicken', 'Haryali Chicken', 650, false, 11),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Chicken', 'Panache Chicken (Chef Special)', 750, false, 12),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Choice of Mutton', 'Panache Mutton (Chef Special)', 1000, false, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Choice of Mutton', 'Handi Mutton', 1000, false, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Choice of Mutton', 'Korma Mutton', 1000, false, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Choice of Mutton', 'Rogan Josh Mutton', 1000, false, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Choice of Mutton', 'Haryali Mutton', 1000, false, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Dal', 'Dal Tadka / Dal Fry', 400, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Dal', 'Dal Makhani', 500, true, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Dal', 'Dal Sultani', 400, true, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Dal', 'Dal Panchmeel', 400, true, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Main – Dal', 'Rajma Rasila', 400, true, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Choices of Vegetable', 'Mix Veg / Sabz Miloni', 450, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Choices of Vegetable', 'Veg Jaipuri', 450, true, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Panache Platters', 'Veg Platter', 900, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Panache Platters', 'Non Veg Platter', 1200, false, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Bread', 'Tawa Roti', 25, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Bread', 'Butter Tawa Roti', 30, true, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Bread', 'Tandoori Roti', 40, true, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Bread', 'Butter Tandoori Roti', 50, true, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Bread', 'Missi Roti', 60, true, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Bread', 'Butter Missi Roti', 70, true, 6),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Bread', 'Plain Naan', 60, true, 7),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Bread', 'Butter Plain Naan', 70, true, 8),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Bread', 'Garlic Naan', 80, true, 9),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Bread', 'Butter Garlic Naan', 90, true, 10),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Bread', 'Laccha Paratha', 90, true, 11),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Indian Bread', 'Butter Chiplets', 50, true, 12),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Rice', 'Steamed / Jeera Rice', 250, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Rice', 'Veg Fried Rice', 350, true, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Rice', 'Butter Onion Rice', 350, true, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Rice', 'Peas Pulao', 350, true, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Rice', 'Veg Pulao', 350, true, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Rice', 'Veg Briyani', 500, true, 6),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Rice', 'Chicken Biryani', 750, false, 7),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Rice', 'Mutton Biryani', 1200, false, 8),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Rice', 'Chicken Fried Rice', 550, false, 9),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Rice', 'Egg Fried Rice', 450, false, 10),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Rice', 'Chilli Garlic Fried Rice', 450, true, 11),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Rice', 'Schezwan Chicken Fried Rice', 650, false, 12),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Italian', 'Alfredo Sauce Pasta', 550, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Italian', 'Arrabita Sauce Pasta', 550, true, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Italian', 'Mixed Sauce Pasta', 550, true, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Italian', 'Mushroom Pizza', 450, true, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Italian', 'Corn Pizza', 350, true, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Italian', 'Plain Pizza', 550, true, 6),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Italian', 'Paneer Peppery', 550, true, 7),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Italian', 'Pizza with Topping of Choice', 550, true, 8),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Italian', 'Margherita Pizza', 550, true, 9),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Kumaoni (Pahadi)', 'Bhat Ki Chudkani / Gahot Ki Dal', 550, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Kumaoni (Pahadi)', 'Mooli Thechuani / Aloo Gutke / Bhat Ke Dupke / Palak Kafa', 350, true, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Kumaoni (Pahadi)', 'Mandua Ki Roti', 60, true, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Kumaoni (Pahadi)', 'Boondi Raita', 150, true, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Kumaoni (Pahadi)', 'Kukumber Raita', 150, true, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Kumaoni (Pahadi)', 'Kumaoni Raita', 150, true, 6),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Kumaoni (Pahadi)', 'Jhungar Ki Kheer', 200, true, 7),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Kumaoni (Pahadi)', 'Kumaoni Badi Ki Sabzi', 350, true, 8),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Kumaoni (Pahadi)', 'Kumaoni Chicken', 700, false, 9),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Kumaoni (Pahadi)', 'Kumaoni Mutton', 1200, false, 10),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Kumaoni (Pahadi)', 'Plain Khichdi', 150, true, 11),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Kumaoni (Pahadi)', 'Moong Dal Khichdi', 150, true, 12),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Dessert', 'Kesari Kheer / Phirni', 150, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Dessert', 'Ice Cream', 150, true, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Dessert', 'Gulab Jamun (2 pcs)', 150, true, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Dessert', 'Rasmalai', 200, true, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Dessert', 'Fruit Custard', 150, true, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Dessert', 'Malpua with Rabri / Shahi Tukda', 200, true, 6),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sandwich', 'Veg Plain Sandwich', 150, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sandwich', 'Chicken Plain Sandwich', 200, false, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sandwich', 'Grill / Club Sandwich', 250, true, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sandwich', 'Chicken Grill Sandwich', 350, false, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sandwich', 'Chocolate Sandwich', 300, true, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sandwich', 'Rainbow Sandwich', 250, true, 6),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sides', 'French Fries', 200, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sides', 'Chilli Cheese Toast', 250, true, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sides', 'Paneer Pakoda', 350, true, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sides', 'Chicken Pakoda', 450, false, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sides', 'Fish Pakoda', 350, false, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sides', 'Masala Maggi', 150, true, 6),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sides', 'Mix Veg Pakora', 250, true, 7),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sides', 'Egg Maggi', 200, false, 8),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sides', 'Peanut Masala', 150, true, 9),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sides', 'Masala Papad', 120, true, 10),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sides', 'Aloo Chat', 150, true, 11),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sides', 'Veg Hakka Noodles', 300, true, 12),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sides', 'Crispy Chidwa', 200, true, 13),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sides', 'Butter Pav Bhaji', 250, true, 14),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sides', 'Veg Burger', 200, true, 15),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sides', 'Chicken Burger', 250, false, 16),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Sides', 'Paneer / Cheese Burger', 250, true, 17),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Beverages', 'Tea', 80, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Beverages', 'Coffee', 120, true, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Beverages', 'Cold Coffee', 200, true, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Beverages', 'Hot Chocolate', 150, true, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Beverages', 'Lassi Sweet / Salt', 150, true, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Beverages', 'Butter Milk', 150, true, 6),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Beverages', 'Aerated Drinks (200 ml)', 50, true, 7),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Beverages', 'Soda', 50, true, 8),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Mocktail Zone', 'Electric Blue', 150, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Mocktail Zone', 'Virgin Mojito', 200, true, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Mocktail Zone', 'Cardamom Cooler', 200, true, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Mocktail Zone', 'Homemade Lemonade', 150, true, 4),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Mocktail Zone', 'Mint Julep', 200, true, 5),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Mocktail Zone', 'Ice Tea', 200, true, 6),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Mocktail Zone', 'Orange Lime Relaxer', 150, true, 7),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Mocktail Zone', 'Atomic Cat', 200, true, 8),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Mocktail Zone', 'Fruit Punch', 200, true, 9),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Mocktail Zone', 'Shirley Temple', 200, true, 10),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Mocktail Zone', 'Buransh Juice', 150, true, 11),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Mocktail Zone', 'Litchi Juice', 150, true, 12),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Mocktail Zone', 'Oreo Shake', 200, true, 13),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Mocktail Zone', 'Elaichi Milk Shake', 200, true, 14),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Mocktail Zone', 'Kesar Milk', 200, true, 15),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Mocktail Zone', 'Plain Milk', 80, true, 16),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Mocktail Zone', 'Coldrinks (750 ml)', 80, true, 17),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Momos', 'Veg Momo', 300, true, 1),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Momos', 'Mushroom Momo', 400, true, 2),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Momos', 'Paneer Momo', 400, true, 3),
((SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'), 'Momos', 'Chicken Momo', 400, false, 4)
"""

categories_map = {
    'Breakfast': '10000000-0000-0000-0000-000000000001',
    'Egg to Order': '10000000-0000-0000-0000-000000000002',
    'Starters – Veg': '10000000-0000-0000-0000-000000000003',
    'Starters – Non-Veg': '10000000-0000-0000-0000-000000000004',
    'Soup': '10000000-0000-0000-0000-000000000005',
    'Salad': '10000000-0000-0000-0000-000000000006',
    'Indian Main – Paneer': '10000000-0000-0000-0000-000000000007',
    'Seasonal Vegetable': '10000000-0000-0000-0000-000000000008',
    'Indian Main – Chicken': '10000000-0000-0000-0000-000000000009',
    'Choice of Mutton': '10000000-0000-0000-0000-000000000010',
    'Indian Main – Dal': '10000000-0000-0000-0000-000000000011',
    'Choices of Vegetable': '10000000-0000-0000-0000-000000000012',
    'Panache Platters': '10000000-0000-0000-0000-000000000013',
    'Indian Bread': '10000000-0000-0000-0000-000000000014',
    'Rice': '10000000-0000-0000-0000-000000000015',
    'Italian': '10000000-0000-0000-0000-000000000016',
    'Kumaoni (Pahadi)': '10000000-0000-0000-0000-000000000017',
    'Dessert': '10000000-0000-0000-0000-000000000018',
    'Sandwich': '10000000-0000-0000-0000-000000000019',
    'Sides': '10000000-0000-0000-0000-000000000020',
    'Beverages': '10000000-0000-0000-0000-000000000021',
    'Mocktail Zone': '10000000-0000-0000-0000-000000000022',
    'Momos': '10000000-0000-0000-0000-000000000023'
}

resort_id = '00000000-0000-0000-0000-000000000001'

out_lines = []
pattern = re.compile(r"\(\(SELECT id FROM restaurants WHERE slug = 'panache-shivalaya'\), '([^']+)', '([^']+)', (\d+), (true|false), (\d+)\)")

for line in old_sql.split('\n'):
    line = line.strip()
    if not line: continue
    
    m = pattern.search(line)
    if m:
        cat_name = m.group(1)
        item_name = m.group(2)
        price = m.group(3)
        veg = m.group(4)
        sort_order = m.group(5)
        
        cat_id = categories_map.get(cat_name)
        if not cat_id:
            print('Missing cat id for', cat_name)
            continue
            
        item_type = 'veg' if veg == 'true' else 'nonveg'
        if cat_name == 'Egg to Order' or 'Egg' in item_name:
            item_type = 'egg'
            
        out_lines.append(f"  ('{resort_id}', '{cat_id}', '{item_name}', {price}, '{item_type}', {sort_order})")

result = "INSERT INTO menu_items (resort_id, category_id, name, price, item_type, sort_order) VALUES\n" + ",\n".join(out_lines) + "\nON CONFLICT DO NOTHING;"
with open('c:/Users/abhay/Desktop/Shivalaya Panache Menu/supabase/gen_menu.sql', 'w', encoding='utf-8') as f:
    f.write(result)
print('Done!')
